# Generated by Django 5.2.3 on 2025-06-21 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=3)),
                ('status', models.CharField(choices=[('A', 'available'), ('N', 'not available')], default='A', max_length=1)),
            ],
        ),
    ]
